<Gerenciador>:
    Menu:
        name: 'menu'
    Tarefas:
        name: 'tarefas'
    Assistente:
        name: 'assistente'
    
<Menu>:
    BoxLayout:
        orientation:'vertical'
        padding:root.width*0.25,root.height*0.1
        spacing:'30dp'
        canvas:
            Color:
                rgba:1,1,1,1
            Rectangle:
                size:self.size
                pos:self.pos
                source:'moldura.png'
        Image:
            source:'logo.png'
            size_hint_y:4
            allow_stretch:True
        Botao:
            text:'Tarefas'
            on_release:app.root.current = 'tarefas'
            cor:0.1,0.1,0.1,1
        Botao:
            text:'Assistente'
            on_release:app.root.current = 'assistente'
        Botao:
            text:'Sair'
            on_release:root.confirmacao()

<Tarefas>:
    BoxLayout:
        orientation:'vertical'
        ActionBar:
            ActionView:
                ActionPrevious:
                    title:'Tarefas'
                    on_release:app.root.current = 'menu'
                ActionButton:
                    text:'Sair'
                    on_release:app.stop()
        ScrollView:
            BoxLayout:
                id:box
                orientation:'vertical'
                size_hint_y:None
                height:self.minimum_height
        BoxLayout:
            size_hint_y:None
            height:'40sp'
            TextInput:
                id:texto
            Button:
                text:'+'
                size_hint_x:None
                width:'40sp'
                on_release:root.addWidget()

<Tarefa>:
    size_hint_y:None
    height:'100sp'
    Label:
        text:root.text
        font_size:'20sp'
    Button:
        text:'X'
        size_hint_x:None
        width:'40sp'
        on_release:app.root.get_screen('tarefas').removeWidget(root)

<Assistente>:
    BoxLayout:
        orientation:'vertical'
        ActionBar:
            ActionView:
                ActionPrevious:
                    title:'Assistente virtual'
                    on_release:app.root.current = 'menu'
                ActionButton:
                    text:'Sair'
                    on_release:app.stop()
        ScrollView:
            BoxLayout:
                id:box
                orientation:'vertical'
                size_hint_y:None
                height:self.minimum_height
        BoxLayout:
            canvas:
                Color:
                    rgba:1,1,1,1
                Rectangle:
                    size:self.size
                    pos:self.pos
            size_hint_y:None
            height:'40sp'
            TextInput:
                id:texto
            Button:
                text:'>'
                size_hint_x:None
                width:'40sp'
                on_release:root.mensagem(texto.text)
            Button:
                background_normal:'mic.png'
                border:0,0,0,0
                size_hint_x:None
                width:'40sp'
                on_release:root.mensagem(texto.text)
